import type { Course, User, Enrollment } from './types'

export const courses: Course[] = [
  {
    id: 'c1',
    title: 'Introduction to Web Development',
    description:
      'Learn the fundamentals of HTML, CSS, and JavaScript. This comprehensive course covers everything you need to build modern websites from scratch. Perfect for beginners who want to start a career in web development.',
    instructor: 'Dr. Sarah Johnson',
    category: 'Web Development',
    level: 'Beginner',
    duration: '8 weeks',
    lessons: 24,
    students: 1250,
    rating: 4.8,
    image: '/placeholder-course.jpg',
    price: 0,
    syllabus: [
      { id: 's1', title: 'HTML Basics & Structure', duration: '45 min', type: 'video' },
      { id: 's2', title: 'CSS Fundamentals', duration: '60 min', type: 'video' },
      { id: 's3', title: 'CSS Layout & Flexbox', duration: '50 min', type: 'video' },
      { id: 's4', title: 'JavaScript Introduction', duration: '55 min', type: 'video' },
      { id: 's5', title: 'DOM Manipulation', duration: '40 min', type: 'reading' },
      { id: 's6', title: 'Module 1 Quiz', duration: '20 min', type: 'quiz' },
    ],
    createdAt: '2025-01-15',
  },
  {
    id: 'c2',
    title: 'React.js - The Complete Guide',
    description:
      'Master React.js including hooks, context API, Redux, and Next.js. Build real-world projects and learn industry best practices for building scalable applications.',
    instructor: 'Prof. Michael Chen',
    category: 'Frontend',
    level: 'Intermediate',
    duration: '12 weeks',
    lessons: 36,
    students: 890,
    rating: 4.9,
    image: '/placeholder-course.jpg',
    price: 49,
    syllabus: [
      { id: 's7', title: 'React Fundamentals & JSX', duration: '50 min', type: 'video' },
      { id: 's8', title: 'Components & Props', duration: '45 min', type: 'video' },
      { id: 's9', title: 'State Management with Hooks', duration: '60 min', type: 'video' },
      { id: 's10', title: 'Context API Deep Dive', duration: '55 min', type: 'video' },
      { id: 's11', title: 'React Router', duration: '40 min', type: 'reading' },
      { id: 's12', title: 'Module 1 Assessment', duration: '30 min', type: 'quiz' },
    ],
    createdAt: '2025-02-01',
  },
  {
    id: 'c3',
    title: 'Data Structures & Algorithms',
    description:
      'Comprehensive course covering all essential data structures and algorithms. Prepare for technical interviews at top tech companies with hands-on coding exercises.',
    instructor: 'Dr. Emily Williams',
    category: 'Computer Science',
    level: 'Intermediate',
    duration: '10 weeks',
    lessons: 30,
    students: 1560,
    rating: 4.7,
    image: '/placeholder-course.jpg',
    price: 39,
    syllabus: [
      { id: 's13', title: 'Arrays & Linked Lists', duration: '55 min', type: 'video' },
      { id: 's14', title: 'Stacks & Queues', duration: '45 min', type: 'video' },
      { id: 's15', title: 'Trees & Graphs', duration: '70 min', type: 'video' },
      { id: 's16', title: 'Sorting Algorithms', duration: '60 min', type: 'video' },
      { id: 's17', title: 'Dynamic Programming', duration: '50 min', type: 'reading' },
      { id: 's18', title: 'Problem Set 1', duration: '45 min', type: 'quiz' },
    ],
    createdAt: '2025-01-20',
  },
  {
    id: 'c4',
    title: 'Python for Data Science',
    description:
      'Learn Python programming with a focus on data science. Cover NumPy, Pandas, Matplotlib, and machine learning basics with scikit-learn.',
    instructor: 'Prof. David Lee',
    category: 'Data Science',
    level: 'Beginner',
    duration: '10 weeks',
    lessons: 28,
    students: 2100,
    rating: 4.6,
    image: '/placeholder-course.jpg',
    price: 29,
    syllabus: [
      { id: 's19', title: 'Python Basics', duration: '50 min', type: 'video' },
      { id: 's20', title: 'NumPy Fundamentals', duration: '45 min', type: 'video' },
      { id: 's21', title: 'Pandas for Data Analysis', duration: '65 min', type: 'video' },
      { id: 's22', title: 'Data Visualization', duration: '55 min', type: 'video' },
      { id: 's23', title: 'Introduction to ML', duration: '60 min', type: 'reading' },
      { id: 's24', title: 'Data Science Quiz', duration: '25 min', type: 'quiz' },
    ],
    createdAt: '2025-03-01',
  },
  {
    id: 'c5',
    title: 'Database Design with MongoDB',
    description:
      'Master NoSQL database design with MongoDB. Learn schema design, aggregation pipelines, indexing strategies, and how to build scalable database solutions.',
    instructor: 'Dr. Sarah Johnson',
    category: 'Backend',
    level: 'Intermediate',
    duration: '6 weeks',
    lessons: 18,
    students: 720,
    rating: 4.5,
    image: '/placeholder-course.jpg',
    price: 35,
    syllabus: [
      { id: 's25', title: 'MongoDB Introduction', duration: '40 min', type: 'video' },
      { id: 's26', title: 'Schema Design Patterns', duration: '55 min', type: 'video' },
      { id: 's27', title: 'CRUD Operations', duration: '50 min', type: 'video' },
      { id: 's28', title: 'Aggregation Framework', duration: '65 min', type: 'video' },
      { id: 's29', title: 'Indexing & Performance', duration: '45 min', type: 'reading' },
      { id: 's30', title: 'Database Design Quiz', duration: '20 min', type: 'quiz' },
    ],
    createdAt: '2025-02-15',
  },
  {
    id: 'c6',
    title: 'Advanced TypeScript Patterns',
    description:
      'Deep dive into TypeScript advanced features. Generics, conditional types, mapped types, and design patterns for building enterprise-grade applications.',
    instructor: 'Prof. Michael Chen',
    category: 'Frontend',
    level: 'Advanced',
    duration: '8 weeks',
    lessons: 22,
    students: 450,
    rating: 4.9,
    image: '/placeholder-course.jpg',
    price: 59,
    syllabus: [
      { id: 's31', title: 'Advanced Generics', duration: '60 min', type: 'video' },
      { id: 's32', title: 'Conditional Types', duration: '55 min', type: 'video' },
      { id: 's33', title: 'Mapped & Utility Types', duration: '50 min', type: 'video' },
      { id: 's34', title: 'Type Guards & Narrowing', duration: '45 min', type: 'video' },
      { id: 's35', title: 'Design Patterns in TS', duration: '70 min', type: 'reading' },
      { id: 's36', title: 'TypeScript Assessment', duration: '35 min', type: 'quiz' },
    ],
    createdAt: '2025-03-10',
  },
]

export const users: User[] = [
  {
    id: 'u1',
    name: 'Alex Student',
    email: 'student@learnhub.com',
    role: 'student',
    enrolledCourses: ['c1', 'c2', 'c4'],
    createdAt: '2025-01-10',
  },
  {
    id: 'u2',
    name: 'Admin User',
    email: 'admin@learnhub.com',
    role: 'admin',
    enrolledCourses: [],
    createdAt: '2025-01-01',
  },
]

export const enrollments: Enrollment[] = [
  {
    courseId: 'c1',
    userId: 'u1',
    progress: 75,
    enrolledAt: '2025-01-20',
    completedLessons: ['s1', 's2', 's3', 's4'],
  },
  {
    courseId: 'c2',
    userId: 'u1',
    progress: 33,
    enrolledAt: '2025-02-05',
    completedLessons: ['s7', 's8'],
  },
  {
    courseId: 'c4',
    userId: 'u1',
    progress: 50,
    enrolledAt: '2025-03-05',
    completedLessons: ['s19', 's20', 's21'],
  },
]

export const categories = [
  'All',
  'Web Development',
  'Frontend',
  'Backend',
  'Data Science',
  'Computer Science',
]
